Feat/get server data
ice-lab/ice-next pull request #288
Opened 2022-06-24 06:12 UTC by chenjun1011

- [ ] feat: getServerData
- [ ] feat: getStaticData https://github.com/ice-lab/ice-next/issues/266
- [ ] fix: Hydrate 时重复调用 getData

2022-06-29 04:16 UTC, luhc228 commented on packages/ice/src/commands/build.ts
> +          isSSG: ssg,
建议是 isSSG -> ssg 不用加 is，有 ts 类型足以说明是一个 boolean

2022-06-29 04:16 UTC, luhc228 commented on packages/ice/template/entry.server.ts.ejs
> +export async function renderToHTML(requestContext, options) {
options 要考虑是 undefined 的情况。建议是 options = {}

2022-07-01 08:20 UTC, chenjun1011 commented on packages/ice/src/service/serverCompiler.ts
> +    if (key === 'process.env.ICE_CORE_SSG' || key === 'process.env.ICE_CORE_SSR') {
没有，这里要把这两个变量过滤掉，不被替换，给运行时用

2022-07-01 08:22 UTC, chenjun1011 commented on packages/ice/src/tasks/web/index.ts
> +      'process.env.ICE_CORE_SSR': false,
改了一下职责
- 原来判断是否需要 hydrate 的逻辑，用 ICE_CORE_RENDER_TYPE 承载，会在构建时被替换
- 新增了 ICE_CORE_SSG、ICE_CORE_SSR 用于运行时判断
   - CSR 时会移除这些代码
   - SSG 和 SSR 时，可以用来判断当前在哪个环境

2022-07-01 08:55 UTC, ClarkXia commented on packages/runtime/src/runServerApp.tsx
> +  if (staticGeneration) {
这个环境变量的初始化建议放到外部处理，比如 entry.server.ts 中

2022-07-01 08:55 UTC, ClarkXia commented on packages/runtime/src/runServerApp.tsx
> +  staticGeneration?: boolean;
这个参数可以考虑是 string 类型的 renderMode: 'ssr' | 'ssg' | 'csr'

2022-07-01 08:55 UTC, ClarkXia commented on packages/runtime/src/routes.tsx
> +      } else if (process.env.ICE_CORE_SSR === 'true') {
这里的处理可以依赖外部传入的 staticGeneration -> renderMode

2022-07-01 10:03 UTC, chenjun1011 commented on packages/ice/template/entry.server.ts.ejs
> -  const appConfig = runtime.getAppConfig(app);
这里的 appConfig 没有调用吗？

2022-07-04 02:48 UTC, ClarkXia approved these changes

2022-07-04 07:02 UTC, luhc228 commented on packages/ice/src/utils/generateHTML.ts
> +      renderMode,
renderMode 能不能在 renderToHTML 内部生成。不然 faas 还要传参数进去

2022-07-04 07:04 UTC, luhc228 requested changes

2022-07-04 07:04 UTC, luhc228 commented on packages/ice/template/entry.server.ts.ejs
> +export async function renderToResponse(requestContext, options = {}) {
options 加一下类型吧

2022-07-04 07:53 UTC, chenjun1011 commented on packages/ice/src/commands/start.ts
> +      if (ssr) {
逻辑不一样，build 时是 SSG 优先，start 时是 SSR 优先

2022-07-04 07:54 UTC, chenjun1011 commented on packages/ice/src/utils/generateHTML.ts
> +      renderMode,
有默认值，renderMode 默认是 SSR，除非不重置为 SSG

2022-07-04 08:27 UTC, merged