Feat: await chunk import in CSR
ice-lab/ice-next pull request #35
Opened 2022-03-18 10:20 UTC by luhc228

#### 背景

路由切换时，之前依赖的是 React.lazy，会先显示 fallback 的效果，然后等待异步 bundle 加载完成后，再显示对应的组件内容。可能会有较长的白屏时间。

#### 方案

点击 Link 组件跳转路由，先发起请求加载对应的 bundle，原来页面的内容保留，加载完成以后，再显示新页面的内容。加载过的 bundle 会存放在 routeModules 对象中，如果已加载过，不会再次加载。

参考：

- https://github.com/remix-run/remix/blob/main/packages/remix-react/transition.ts
- https://github.com/remix-run/remix/blob/main/packages/remix-react/browser.tsx
- https://github.com/remix-run/remix/blob/main/packages/remix-react/server.tsx

#### 其他变更点

1. `runApp.tsx` 修改为 `runBrowserApp.tsx`，与 `runServerApp.tsx` 对齐
2. 删除 render.tsx 和 serverRender.tsx，`render.tsx` 和 `serverRender.tsx` 分别放在 `runBrowserApp.tsx` 和 `runServerApp.tsx ` 中
3. 抽离默认的 appConfig 到 defaultAppConfig.ts，方便在 server 和 browser 端中统一消费
4. 生成最终给 react-router 消费的 routes 对象在 server 和 browser 端的逻辑是一致的，因此在临时目录下只需保留一份 routes.ts

2022-03-21 07:24 UTC, imsobear requested changes

2022-03-21 07:24 UTC, imsobear commented on packages/runtime/src/runBrowserApp.tsx
> +  await Promise.all(matchRoutes.map(match => loadRouteModule(match.route as RouteItem, routeModules)));
同理，这里能不能设计成 `const routeModules = await loadRoutesModules(matchRoutes);`

2022-03-21 07:24 UTC, imsobear commented on packages/runtime/src/runBrowserApp.tsx
> +  const render = isSSR ? ReactDOM.hydrate : runtime.getRender();
这个逻辑是不是应该放在 runtime.getRender 里？

2022-03-21 07:24 UTC, imsobear commented on packages/runtime/src/runBrowserApp.tsx
> +  }
这块写的也有点冗余，可以考虑把设置默认值直接放在 runtime 里，然后这里只需要 get，跟上面的 render 一样。

2022-03-21 07:24 UTC, imsobear commented on packages/runtime/src/runBrowserApp.tsx
> +  return rootId ? document.getElementById(rootId) : document.getElementById('ice-container');
rootId 应该一定会有？

2022-03-21 07:24 UTC, imsobear commented on packages/runtime/src/runBrowserApp.tsx
> +  return rootId ? document.getElementById(rootId) : document.getElementById('ice-container');
可以考虑把默认值直接设置成  ice-container，这里就不用绕来绕去的了。

2022-03-21 07:24 UTC, imsobear commented on packages/runtime/src/runBrowserApp.tsx
> +    appContext.initialData = await appConfig.app.getInitialData(initialContext);
initialContext 和 requestContext 需要统一成一个概念和类型。

2022-03-21 07:24 UTC, imsobear commented on packages/runtime/src/runBrowserApp.tsx
> +function BrowserComponent({ runtime, routerType }: { runtime: Runtime; routerType: AppConfig['router']['type'] }) {
适当加点注释，比如这个组件几块主要做了什么

2022-03-21 07:24 UTC, imsobear commented on packages/runtime/src/routes.tsx
> +}
这几个方法加下基本的注释说明。

2022-03-21 07:24 UTC, imsobear commented on packages/runtime/src/App.tsx
> +  );
这里的 client 怎么理解？

2022-03-21 07:24 UTC, imsobear commented on packages/runtime/src/App.tsx
> +    element = routes[0].element;
这里可以加个 TODO 注释，这种情况需要清空各种 react-dom-router、history 相关依赖。

2022-03-21 07:24 UTC, imsobear commented on packages/runtime/src/App.tsx
>    }
这里一堆路由相关的功能有没有可能移到 AppRouter 里？通过 appContext 搭车透传 routes 职责上有点混乱。

2022-03-21 07:24 UTC, imsobear commented on packages/runtime/src/App.tsx
> +    element = routes[0].element;
这里怎么更好的设计也要看下，牵扯到 runXXXApp 的设计。

2022-03-21 12:30 UTC, chenjun1011 commented on packages/ice/template/entry.client.ts.ejs
> +import { runBrowserApp } from '@ice/runtime';
我们的入口是 entry.client.ts ，是不是要对应 runClientApp？

2022-03-21 12:43 UTC, chenjun1011 commented on packages/runtime/src/runBrowserApp.tsx
> +  const appConfig: AppConfig = merge(defaultAppConfig, config);
记得之前说要设计个 defineAppConfig 方法？

2022-03-21 12:54 UTC, chenjun1011 commented on packages/runtime/src/runBrowserApp.tsx
> +    <BrowserComponent
BrowserEntry 怎么样？

或者把  BrowserComponent  这部分的逻辑 合并到 render 里，就不需要再包一层组件了

render 函数里本身好像有没有什么逻辑，省的 runtime 一层层透传了

2022-03-21 12:56 UTC, chenjun1011 commented on packages/runtime/src/runServerApp.tsx
> + let staticNavigator = {
这里能不能单独抽成一个方法？

2022-03-22 02:01 UTC, imsobear commented on packages/runtime/src/runBrowserApp.tsx
> +    <BrowserComponent
另外这个 BrowserComponent 是不在 Strict 里的

2022-03-22 02:02 UTC, imsobear commented on packages/runtime/src/runBrowserApp.tsx
> +import { merge } from 'lodash-es';
虽然有 tree-shaking 但是也只是 build 的时候才生效，可以考虑用小包。

2022-03-22 02:02 UTC, imsobear commented on packages/ice/template/entry.client.ts.ejs
> +import { runBrowserApp } from '@ice/runtime';
要不概念就统一成 browser？

2022-03-22 02:44 UTC, imsobear commented on packages/runtime/src/runBrowserApp.tsx
> +import { merge } from 'lodash-es';
的确，简单合并下就可以，确定性比较强的

2022-03-22 03:05 UTC, ClarkXia commented on packages/runtime/src/RouteWrapper.tsx
> +  const { pageData } = useAppContext();
如果是 page 级别的数据，直接挂在顶层 App 上是否合适，页面切换时是不是应该尽量不去更新整个 App

2022-03-22 06:59 UTC, luhc228 commented on packages/runtime/src/runServerApp.tsx
>    ) {
fixed

2022-03-22 06:59 UTC, luhc228 commented on packages/runtime/src/runServerApp.tsx
>  export default async function runServerApp(
done

2022-03-22 07:00 UTC, luhc228 commented on packages/runtime/src/runBrowserApp.tsx
> +  }
fixed

2022-03-22 07:00 UTC, luhc228 commented on packages/runtime/src/runBrowserApp.tsx
> +  return rootId ? document.getElementById(rootId) : document.getElementById('ice-container');
fixed

2022-03-22 07:01 UTC, luhc228 commented on packages/runtime/src/App.tsx
> +    element = routes[0].element;
现在先加了 TODO

2022-03-22 07:01 UTC, luhc228 commented on packages/ice/template/entry.client.ts.ejs
> +import { runBrowserApp } from '@ice/runtime';
改成 entry.browser.ts

2022-03-22 07:01 UTC, luhc228 commented on packages/runtime/src/runBrowserApp.tsx
> +import { merge } from 'lodash-es';
已移除 lodash-es

2022-03-22 07:02 UTC, luhc228 commented on packages/runtime/src/runServerApp.tsx
> + let staticNavigator = {
done

2022-03-22 07:02 UTC, luhc228 commented on packages/ice/src/routes.ts
> +  return { routesStr };
fixed

2022-03-22 07:04 UTC, luhc228 commented on packages/runtime/src/runBrowserApp.tsx
> +import { merge } from 'lodash-es';
fixed

2022-03-22 07:05 UTC, luhc228 commented on packages/runtime/src/App.tsx
> +  const { appConfig, routes, routeModules, pageData: initPageData } = appContext;
runBrowserApp 和 runServerApp 都会通过 appContext 传进来初始化 pageData

2022-03-22 07:09 UTC, luhc228 commented on packages/ice/template/entry.client.ts.ejs
> +runBrowserApp(appConfig, runtimeModules, routes);
不能使用 runBrowserApp？

2022-03-22 07:13 UTC, luhc228 commented on packages/runtime/src/runBrowserApp.tsx
> +    <BrowserComponent
现在先改成 BrowserEntry。没有 BrowserEntry 是最好的，让上面的逻辑都在 app.tsx 中，但是遇到一个问题是 useLayoutEffect 不能在 server 端中调用，需要再一下怎么优化

2022-03-22 07:13 UTC, luhc228 commented on packages/runtime/src/runBrowserApp.tsx
> +  const appConfig: AppConfig = merge(defaultAppConfig, config);
已添加

2022-03-22 07:13 UTC, luhc228 commented on packages/runtime/src/App.tsx
>    }
现在已经没有透传修改后的 routes 了

2022-03-22 07:13 UTC, luhc228 commented on packages/runtime/src/App.tsx
> +  );
改成 routes 。

2022-03-22 07:58 UTC, luhc228 commented on packages/runtime/src/RouteWrapper.tsx
> +  const { pageData } = useAppContext();
现在是要在 App 组件之前监听 history.location 的变化的。后面可以看下怎么优化下如果不更新整个 APP

2022-03-22 08:32 UTC, luhc228 commented on packages/runtime/src/runBrowserApp.tsx
> +  await Promise.all(matchRoutes.map(match => loadRouteModule(match.route as RouteItem, routeModules)));
fixed

2022-03-22 08:32 UTC, luhc228 commented on packages/runtime/src/runServerApp.tsx
> +  await createRouteModules(routes, routeModules);
fixed

2022-03-22 08:32 UTC, luhc228 commented on packages/runtime/src/runBrowserApp.tsx
> +function BrowserComponent({ runtime, routerType }: { runtime: Runtime; routerType: AppConfig['router']['type'] }) {
done

2022-03-22 08:33 UTC, luhc228 commented on packages/runtime/src/routes.tsx
> +}
done

2022-03-22 08:33 UTC, luhc228 commented on packages/runtime/src/App.tsx
> +  const [, setClientState] = useState({});
fixed

2022-03-22 08:33 UTC, luhc228 commented on packages/runtime/src/routes.tsx
> +  throw new Error(
done

2022-03-22 08:33 UTC, luhc228 commented on packages/runtime/src/routes.tsx
> +function DefaultRouteComponent({ id }: { id: string }): JSX.Element {
fixed

2022-03-22 09:16 UTC, luhc228 commented on packages/runtime/src/runBrowserApp.tsx
> +    appContext.initialData = await appConfig.app.getInitialData(initialContext);
把二者都统一了一下类型了

2022-03-22 09:22 UTC, imsobear approved these changes

2022-03-22 09:23 UTC, merged