fix: improve framework config
ice-lab/ice-next pull request #36
Opened 2022-03-21 07:19 UTC by ClarkXia

- [x] improve webpack config
- [x] support user config

2022-03-22 03:15 UTC, imsobear requested changes

2022-03-22 03:15 UTC, imsobear commented on packages/build-webpack-config/src/index.ts
>            minify: TerserPlugin.esbuildMinify,
如何保证 esbuild 版本一致性，可以记录个 issue

2022-03-22 03:15 UTC, imsobear commented on packages/build-webpack-config/src/index.ts
> +          parallel: experimental?.parallel || false,
为什么要放在试验特性下？会有什么副作用？

2022-03-22 03:15 UTC, imsobear commented on packages/build-webpack-config/src/index.ts
> +          minimizerOptions,
CSS 压缩这块可以记录个 issue，后面看看有没有更快的选择。

2022-03-22 03:15 UTC, imsobear commented on packages/build-webpack-config/src/index.ts
> +          minimizerOptions,
CSS 压缩这块可以记录个 issue，后面看看有没有更快的选择。

2022-03-22 03:15 UTC, imsobear commented on packages/build-webpack-config/src/index.ts
> +
这个空行没有意义。

2022-03-22 03:15 UTC, imsobear commented on packages/build-webpack-config/src/index.ts
> +  } catch {}
建议打个 warning，不然挂了都不知道。

2022-03-22 03:15 UTC, imsobear commented on packages/build-webpack-config/src/plugins/swc.ts
> +  const commonOptions: SwcConfig = {
这个插件叫 swc 是不合理的，可以包含实现（swc），但核心应该要表达出插件的作用。

2022-03-22 03:15 UTC, imsobear commented on packages/plugin-app/src/index.ts
> +  const mode: 'development' | 'production' = command === 'start' ? 'development' : 'production';
这个类型应该能自动推导出来。

2022-03-22 03:15 UTC, imsobear commented on packages/plugin-app/src/index.ts
> +  registerUserConfig(userConfig);
越来越倾向于把三个事情放在 ice 这个主包里，感觉代码逻辑会清晰不少，插件可以有这个能力，但只是为了补充，核心部分应该在主包（service）里完成。

2022-03-22 03:38 UTC, ClarkXia commented on examples/basic-project/build.json
> +  }
测试的 alias

2022-03-22 03:39 UTC, ClarkXia commented on examples/basic-project/src/document.tsx
> +        <script src="./index.js"></script>
配置 entry 的时候默认做了一个简单的分包策略（后续还需要优化），runtime 中包含 react react-dom @ice/runtime 的代码

2022-03-22 03:57 UTC, ClarkXia commented on packages/build-webpack-config/src/index.ts
>            minify: TerserPlugin.esbuildMinify,
TerserPlugin 的 esbuild 目前是作为 peerDependencies，在 ice 层面保障 ebuild 的使用版本即可

2022-03-22 04:09 UTC, ClarkXia commented on packages/build-webpack-config/src/index.ts
> +  })[0];
src 目录下存在 entry.client.ts 文件，则已这个文件为 entry 入口

2022-03-22 04:09 UTC, ClarkXia commented on packages/build-webpack-config/src/index.ts
> +  })[0];
src 目录下存在 entry.client.ts 文件，则已这个文件为 entry 入口

2022-03-22 04:10 UTC, ClarkXia commented on packages/build-webpack-config/src/config/css.ts
> +        ['@builder/pack/deps/postcss-preset-env', {
已记录 issue

2022-03-22 04:12 UTC, ClarkXia commented on packages/build-webpack-config/src/index.ts
> +          parallel: experimental?.parallel || false,
parallel 除了 true 之外 还可以指定 number（存在 Error: Call retries were exceeded 的风险），之前考虑多个地方启动 parallel 能力，目前配置上暂不需要。

2022-03-22 04:12 UTC, ClarkXia commented on packages/build-webpack-config/src/index.ts
> +          minimizerOptions,
已记录 issue

2022-03-22 04:12 UTC, ClarkXia commented on packages/build-webpack-config/src/index.ts
> +
fixed

2022-03-22 04:13 UTC, ClarkXia commented on packages/build-webpack-config/src/index.ts
> +  } catch {}
先打 debug，默认情况下不存在 browsers 配置 load 也会报错

2022-03-22 04:13 UTC, ClarkXia commented on packages/plugin-app/src/index.ts
> +  const mode: 'development' | 'production' = command === 'start' ? 'development' : 'production';
fixed

2022-03-22 04:13 UTC, ClarkXia commented on packages/build-webpack-config/src/plugins/swc.ts
> +  const commonOptions: SwcConfig = {
先叫 compilation

2022-03-22 05:46 UTC, ClarkXia commented on packages/plugin-app/src/index.ts
> +  registerUserConfig(userConfig);
可以后面单独讨论明确下各个包的职责边界

2022-03-22 08:30 UTC, ClarkXia commented on packages/build-webpack-config/src/index.ts
> +  })[0];
已修复成 `path.join(rootDir, 'src')`

2022-03-22 08:30 UTC, ClarkXia commented on packages/build-webpack-config/src/index.ts
> +  })[0];
已修复成 `path.join(rootDir, 'src')`

2022-03-23 03:42 UTC, luhc228 commented on packages/build-webpack-config/src/plugins/compilation.ts
> +const compilationPlugin = (options: Options): UnpluginOptions => {
重命名为 compilationPlugin 是因为跟模块的编译相关？

2022-03-23 03:43 UTC, luhc228 commented on packages/build-webpack-config/src/plugins/compilation.ts
> +      // @ts-expect-error
为什么呢？补充下原因吧

2022-03-23 05:18 UTC, ClarkXia commented on packages/build-webpack-config/src/plugins/compilation.ts
> +const compilationPlugin = (options: Options): UnpluginOptions => {
是的 之前觉得 swc 的命名无法清楚说明这个插件的职责

2022-03-23 05:23 UTC, ClarkXia commented on packages/build-webpack-config/src/plugins/compilation.ts
> +      // @ts-expect-error
已补充 @builder/swc 的类型问题

2022-03-28 11:34 UTC, ClarkXia commented on examples/basic-project/src/document.tsx
> +        <script src="./index.js"></script>
目前已可以通过 AssetsMainfest 自动添加

2022-03-28 11:43 UTC, imsobear approved these changes

2022-03-29 02:26 UTC, luhc228 approved these changes

2022-03-29 02:29 UTC, merged