fix: assets order
ice-lab/ice-next pull request #470
Opened 2022-08-19 09:33 UTC by chenjun1011

fix https://github.com/ice-lab/ice-next/issues/459 中的问题1

2022-08-22 05:47 UTC, ClarkXia requested changes

2022-08-22 05:47 UTC, ClarkXia commented on packages/runtime/src/Document.tsx
> +  const scripts = entryAssets.concat(pageAssets).filter(path => path.indexOf('.js') > -1);
不能直接这样改， entry 资源在前的情况下加载完会直接触发 chunk 的加载，而实际上页面上已经输出了 chunk 资源会导致重复加载问题

2022-08-25 03:12 UTC, ClarkXia approved these changes

2022-08-25 04:20 UTC, wssgcg1213 approved these changes

2022-08-25 05:51 UTC, merged